from collections import Counter
from pathlib import Path

from services.markdown_parser import (
    get_image_sources,
)


def validate_final_images(
    markdown: str,
    *,
    image_results: list[dict],
) -> list[str]:
    errors: list[str] = []

    references = get_image_sources(markdown)
    reference_counts = Counter(references)

    inserted_results = [
        result for result in image_results if result["status"] == "inserted"
    ]

    expected_counts = Counter(result["markdown_path"] for result in inserted_results)

    # Every generated image must be embedded exactly once.
    for path, expected_count in expected_counts.items():
        if expected_count > 1:
            errors.append(
                f"Multiple generated images use the same Markdown path: {path}"
            )

        actual_count = reference_counts[path]

        if actual_count == 0:
            errors.append(f"Generated image is not embedded: {path}")

        elif actual_count > 1:
            errors.append(
                "Generated image is embedded multiple "
                f"times: {path} "
                f"(count={actual_count})"
            )

    generated_markdown_paths = set(expected_counts)

    # Generated assets are still in staging here.
    for result in inserted_results:
        staged_value = result.get("staged_path")
        published_value = result.get("published_path")

        if not staged_value:
            errors.append(f"Image {result['id']} is missing staged_path.")
            continue

        if not published_value:
            errors.append(f"Image {result['id']} is missing published_path.")
            continue

        staged_path = Path(staged_value)

        if not staged_path.is_file():
            errors.append(f"Staged generated image does not exist: {staged_value}")

        elif staged_path.stat().st_size == 0:
            errors.append(f"Staged generated image is empty: {staged_value}")

        # The final filesystem destination must match
        # the path already embedded in Markdown.
        markdown_target = (Path("generated_blogs") / result["markdown_path"]).resolve()

        published_path = Path(published_value).resolve()

        if published_path != markdown_target:
            errors.append(
                "Published image path does not match "
                "Markdown path: "
                f"{published_value} != "
                f"{result['markdown_path']}"
            )

    # A local image not generated by this run must
    # already exist at its referenced location.
    for path in reference_counts:
        if path.startswith(
            (
                "http://",
                "https://",
            )
        ):
            continue

        if path in generated_markdown_paths:
            continue

        filesystem_path = (Path("generated_blogs") / path).resolve()

        if not filesystem_path.exists():
            errors.append(f"Referenced image does not exist: {path}")

    for result in image_results:
        if result["status"] != "inserted":
            errors.append(f"Image {result['id']} was not inserted.")

    return errors
