"""add_article_markdown_and_assets

Revision ID: 23d85ff68c2f
Revises: ad9bbd19cc00
Create Date: 2026-09-27 20:59:20.950603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23d85ff68c2f'
down_revision: Union[str, Sequence[str], None] = 'ad9bbd19cc00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runs', sa.Column('article_markdown', sa.Text(), nullable=True))
    op.add_column('runs', sa.Column('article_assets', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('runs', 'article_assets')
    op.drop_column('runs', 'article_markdown')
    # ### end Alembic commands ###
