"""add client_ip_hash and drop article_object_key

Revision ID: 9b0360da6e83
Revises: 23d85ff68c2f
Create Date: 2026-09-28 14:53:44.639696

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9b0360da6e83"
down_revision: str | Sequence[str] | None = "23d85ff68c2f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "runs", sa.Column("client_ip_hash", sa.String(length=64), nullable=True)
    )
    op.create_index(
        op.f("ix_runs_client_ip_hash"), "runs", ["client_ip_hash"], unique=False
    )
    op.drop_column("runs", "article_object_key")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "runs",
        sa.Column("article_object_key", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.drop_index(op.f("ix_runs_client_ip_hash"), table_name="runs")
    op.drop_column("runs", "client_ip_hash")
    # ### end Alembic commands ###
