"""create_rate_limit_buckets

Revision ID: ad9bbd19cc00
Revises: ab7e458eee02
Create Date: 2026-09-27 17:07:40.766877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad9bbd19cc00'
down_revision: Union[str, Sequence[str], None] = 'ab7e458eee02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rate_limit_buckets',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('bucket_key', sa.String(length=64), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rate_limit_buckets_bucket_key'), 'rate_limit_buckets', ['bucket_key'], unique=True)
    op.create_index(op.f('ix_rate_limit_buckets_expires_at'), 'rate_limit_buckets', ['expires_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rate_limit_buckets_expires_at'), table_name='rate_limit_buckets')
    op.drop_index(op.f('ix_rate_limit_buckets_bucket_key'), table_name='rate_limit_buckets')
    op.drop_table('rate_limit_buckets')
    # ### end Alembic commands ###
